export const INTRO = "Intro";
export const LOGIN = "Login";
export const SIGNUP = "Signup"
export const ANSWER = "Answer";
export const FRIENDS = "Friends";
export const COMMENTS = "Comments";
export const CHAT_ROOM = "ChatRoom";
export const WRITE_WORRY = "WriteWorry";
export const DETAIL_POST = "DetailPost";
export const WRITE_COMMENT = "WriteComment";
export const USER_INFO_ROOM = "UserInfoRoom";
export const MY_POST_STORAGE = "MyPostStorage";
export const COUNSELING_CENTER = "CounselingCenter";
export const BOTTOM_TAB_NAVIGATION = "BottomTabNavigation";

export const FRIENDS_LABEL = "나의 인연들";
export const WRITE_WORRYLABEL = "글 쓰기";
export const USER_INFO_ROOMLABEL = "내 정보";
export const MY_POST_STORAGELABEL = "내 마음 저장소";
export const COUNSELING_CENTERLABEL = "고민 상담소";
